name: Tests
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4.5.0
      - run: nimble install -y --verbose
      - run: nimble test --verbose
